name: ever
description: Ever app with reactive architecture and resilience patterns.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  isar: ^3.1.0+1
  synchronized: ^3.1.0

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0 